/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Cobuyr(props) {
  const { nodes, materials } = useGLTF("./cobuyr.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Rhand"
        castShadow
        receiveShadow
        geometry={nodes.hends.geometry}
        material={materials["Gold Wave"]}
      />
      <mesh
        name="Lhand"
        castShadow
        receiveShadow
        geometry={nodes.hends001.geometry}
        material={materials["Ghost 2"]}
      />
      <mesh
        name="Ring"
        // castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Wave 2"]}
      />
    </group>
  );
}

useGLTF.preload("/cobuyr.glb");
